### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by KingIzzymon**
I completed updating documentation to todays code.

* Updated main page to include "not affiliated with linuxserver/emulatorjs"
* Added several pages under "Docs" section
* Added Roadmap & News pages to keep community informed
* Included link to the project changelog
* Organized the files into "docs" and "docs4devs" folders to mimic website for ease of editing

### CODE REVIEW

**Comment by ethanaobrien** [comment]
I made some comments for questions I had. Could you also delete the `src/.vuepress/public/data/` folder, since this is no longer needed (because I put the demo in its own domain)

**Comment by KingIzzymon** [comment]
Hey boss, I'm having trouble finding your comments. Where did you put them?

**Comment by ethanaobrien** [comment]
I commented on the commits, you should be able to see it in the files changed tab or the conversation tab

**Comment by KingIzzymon** [comment]
I might be having a blonde moment here since I havent used github in a while... but I've checked through this conversation tab and through each of my commits in the commit tab and still cant find your comments.


Capture

**Comment by ethanaobrien** [comment]
If you scroll down a bit
Screenshot 2022-11-13 1 51 09 PM

**Comment by KingIzzymon** [comment]
This is so weird, its not showing up for me. I never even got notifications of your comments...

**Comment by ethanaobrien** [comment]
Strange, do you want me to just send you screenshots of everything?

**Comment by KingIzzymon** [comment]
Sure if its not too much trouble, but I still wanna know why I cant see comments or if others can.

**Comment by ethanaobrien** [comment]
I looked, not sure why I'm the only one that can see it but it is a problem. This is really weird

**Comment by ethanaobrien** [comment]
Screenshot 2022-11-13 2 06 40 PM
Screenshot 2022-11-13 2 06 49 PM
Screenshot 2022-11-13 2 07 09 PM
Screenshot 2022-11-13 2 07 24 PM
Screenshot 2022-11-13 2 07 35 PM
Screenshot 2022-11-13 2 07 41 PM
Screenshot 2022-11-13 2 07 46 PM
Screenshot 2022-11-13 2 07 56 PM
Screenshot 2022-11-13 2 08 02 PM

**Comment by KingIzzymon** [comment]
Quick question, who actually created this logo? Having you or linuxserver/emulatorjs change their logo to something different would help alot with the confusion.

logo

**Comment by ethanaobrien** [comment]
I'm not completely sure, allancoding got the logo. If you could make a new logo I'd appreciate that

**Comment by KingIzzymon** [comment]
Sure thing, I'll work on that after the documentation.

Should I open a new issue and submit my drafts there? To keep the conversations concise.

**Comment by ethanaobrien** [comment]
Sure, whatever you prefer.

**Comment by KingIzzymon** [comment]
Which file has the `right": "50%` typos?

**Comment by KingIzzymon** [comment]
Alright, that should be it.

## Summary

For npm's "package.json" file, they don't allow an author array, but I made a contributors array and added myself and Allan.

Regarding the "Client setup" sections, its just describes how to make a shortcut on your home page on a phone or, for the steam deck, to open chrome in kiosk mode (works on windows too). Give it a try and test with something like youtube.

I removed the "Basic controls" section. It was leftover from when I thought you were the linuxserver version...

The issue you mentioned about retroachievements, is that coming all the way from libretro? I use retroachievements and it requires internet while playing, downloads your current achievements on launch and autoupdates as you unlock more. At least that's how I believe it works... I'm definitely interested in learning more.

**Comment by ethanaobrien** [comment]
>The issue you mentioned about retroachievements, is that coming all the way from libretro? I use retroachievements and it requires internet while playing, downloads your current achievements on launch and autoupdates as you unlock more. At least that's how I believe it works... I'm definitely interested in learning more.

I didn't know this. I'll look more into this when I can

**Comment by ethanaobrien** [comment]
Looks good! Thank you for your help!

**Pull request merged**
